name: Update README with Most Used Languages

on:
  schedule:
    - cron: '0 0 * * *'  # Update daily at midnight
  workflow_dispatch:  # Trigger manually

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Generate README Stats
      run: |
        curl -s https://github-readme-stats.vercel.app/api/top-langs?username=jheelamH&show_icons=true&layout=compact&count_private=true > stats.svg

    - name: Update README file
      run: |
        echo "![Most Used Languages](./stats.svg)" >> README.md
        git add README.md
        git commit -m "Update most used languages"
        git push

